services:
  # Background Worker (Scheduler)
  - type: worker
    name: ai-report-scheduler
    env: python
    region: oregon
    plan: starter  # Free tier
    buildCommand: pip install -r requirements.txt
    startCommand: python scheduler.py
    
    # Persistent disk for ChromaDB
    disk:
      name: chromadb-storage
      mountPath: /app/chroma_db
      sizeGB: 1
    
    # Environment variables (set these in Render dashboard)
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: RECIPIENT_EMAIL
        sync: false
      - key: TELEGRAM_API_ID
        sync: false
      - key: TELEGRAM_API_HASH
        sync: false
      - key: TELEGRAM_PHONE
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0

