"""
View Microsoft AutoGen agent conversations in real-time
"""
from agent import generate_report_with_autogen_multiagent
import sys

print("\n" + "="*80)
print("MICROSOFT AUTOGEN MULTI-AGENT CONVERSATION VIEWER")
print("="*80)
print("\nThis will show the complete conversation between agents:\n")
print("  1. User Proxy sends query to Data Analyst")
print("  2. Data Analyst analyzes and responds")
print("  3. User Proxy sends findings to Report Writer")
print("  4. Report Writer creates final report")
print("\n" + "="*80 + "\n")

# Run multi-agent system with visible conversation
query = "Analyze top performing products and marketing channels in Q3 2024"

print(f"QUERY: {query}")
print("\n" + "="*80)
print("AGENT CONVERSATION STARTS BELOW")
print("="*80 + "\n")

# This will print all agent interactions
report = generate_report_with_autogen_multiagent(query, "combined", n_results=8)

print("\n" + "="*80)
print("FINAL REPORT GENERATED BY AGENTS")
print("="*80)
print(report)

print("\n" + "="*80)
print("CONVERSATION COMPLETE")
print("="*80)

